name: daily_expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # UI/UX
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_styled_toast: ^2.2.1
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  fl_chart: ^0.70.2

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Data Handling
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Networking
  cached_network_image: ^3.3.1
  internet_connection_checker: ^3.0.1

  #freezed
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

  # Utility
  get_it: ^8.0.3
  uuid: ^4.3.3

  # User Authentication
  auth_user:
    path: packages/auth_user
  user_service:
    path: packages/user_service

  # Database
  db_firestore_client:
    path: packages/db_firestore_client
  db_hive_client:
    path: packages/db_hive_client

  # Parsing and Serialization
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Others
  pattern_formatter: ^4.0.0

dev_dependencies:
  # Linting
  flutter_lints: ^5.0.0

  # Testing
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

  # Asset Generation
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/icons/main_app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
