// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-9IDFSRCB50fr4sWRL_tns7-kFKPvnc',
    appId: '1:942263604820:android:70aafd237698eb7ea6ffc1',
    messagingSenderId: '942263604820',
    projectId: 'daily-expense-tracker-v1',
    databaseURL: 'https://daily-expense-tracker-v1-default-rtdb.firebaseio.com',
    storageBucket: 'daily-expense-tracker-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Paljva95NlvAD7J3ceMp0EgZeQdN3Ro',
    appId: '1:942263604820:ios:77200f9f134ba543a6ffc1',
    messagingSenderId: '942263604820',
    projectId: 'daily-expense-tracker-v1',
    databaseURL: 'https://daily-expense-tracker-v1-default-rtdb.firebaseio.com',
    storageBucket: 'daily-expense-tracker-v1.firebasestorage.app',
    androidClientId: '942263604820-05vuo534iaonpehie5q0k0rag4j6td0h.apps.googleusercontent.com',
    iosClientId: '942263604820-7kg310l6j50ubacud66gtej4cuvkcaj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyExpenseTrackerApp',
  );
}
